/**
 * Curated searchable emoji set for the Stamp tool. No API key or network
 * request required — rendered as SVG text (see emojiToDataUrl) so it can be
 * stamped onto the canvas exactly like icons and GIFs.
 */
export const EMOJIS = [
  { emoji: '😀', name: 'Grinning Face', keywords: 'happy smile face' },
  { emoji: '😂', name: 'Tears of Joy', keywords: 'laugh cry funny lol' },
  { emoji: '🥰', name: 'Smiling Face with Hearts', keywords: 'love adore' },
  { emoji: '😎', name: 'Cool Face', keywords: 'sunglasses cool swag' },
  { emoji: '🤔', name: 'Thinking Face', keywords: 'think hmm ponder' },
  { emoji: '😭', name: 'Crying Face', keywords: 'sad tears sob' },
  { emoji: '😡', name: 'Angry Face', keywords: 'mad rage furious' },
  { emoji: '😴', name: 'Sleeping Face', keywords: 'sleep tired zzz' },
  { emoji: '🥳', name: 'Party Face', keywords: 'party celebrate birthday' },
  { emoji: '😱', name: 'Screaming Face', keywords: 'shocked scared fear' },
  { emoji: '🤯', name: 'Mind Blown', keywords: 'shocked explode surprised' },
  { emoji: '😇', name: 'Angel Face', keywords: 'innocent halo good' },
  { emoji: '🥺', name: 'Pleading Face', keywords: 'puppy eyes beg please' },
  { emoji: '😏', name: 'Smirking Face', keywords: 'smug sly' },
  { emoji: '🙃', name: 'Upside Down Face', keywords: 'silly sarcasm' },
  { emoji: '😅', name: 'Sweat Smile', keywords: 'nervous relief phew' },
  { emoji: '🤩', name: 'Star Struck', keywords: 'excited amazed wow' },
  { emoji: '😢', name: 'Sad Face', keywords: 'tear unhappy cry' },
  { emoji: '🤗', name: 'Hugging Face', keywords: 'hug embrace' },
  { emoji: '🤫', name: 'Shushing Face', keywords: 'quiet secret shh' },
  { emoji: '🧠', name: 'Brain', keywords: 'brain mind smart think idea' },
  { emoji: '👀', name: 'Eyes', keywords: 'eyes look watch see' },
  { emoji: '👁️', name: 'Eye', keywords: 'eye see look' },
  { emoji: '👄', name: 'Mouth', keywords: 'mouth lips' },
  { emoji: '👅', name: 'Tongue', keywords: 'tongue taste' },
  { emoji: '🦷', name: 'Tooth', keywords: 'tooth dentist teeth' },
  { emoji: '👂', name: 'Ear', keywords: 'ear hear' },
  { emoji: '👃', name: 'Nose', keywords: 'nose smell' },
  { emoji: '💪', name: 'Flexed Bicep', keywords: 'muscle strong arm gym' },
  { emoji: '🦴', name: 'Bone', keywords: 'bone skeleton' },
  { emoji: '❤️', name: 'Red Heart', keywords: 'love heart' },
  { emoji: '💔', name: 'Broken Heart', keywords: 'heartbreak sad breakup' },
  { emoji: '💯', name: 'Hundred Points', keywords: '100 perfect score' },
  { emoji: '🔥', name: 'Fire', keywords: 'hot lit flame trending burn' },
  { emoji: '⭐', name: 'Star', keywords: 'star favorite rating night sky' },
  { emoji: '✨', name: 'Sparkles', keywords: 'shiny magic new' },
  { emoji: '💧', name: 'Droplet', keywords: 'water sweat tear' },
  { emoji: '💥', name: 'Collision', keywords: 'boom explosion bang' },
  { emoji: '💤', name: 'Zzz', keywords: 'sleep tired snore' },
  { emoji: '💨', name: 'Dash', keywords: 'fast wind run speed' },
  { emoji: '🎉', name: 'Party Popper', keywords: 'celebrate confetti party' },
  { emoji: '🎊', name: 'Confetti Ball', keywords: 'celebrate party' },
  { emoji: '🏆', name: 'Trophy', keywords: 'win award champion' },
  { emoji: '🥇', name: 'Gold Medal', keywords: 'first winner award' },
  { emoji: '👍', name: 'Thumbs Up', keywords: 'like good approve yes' },
  { emoji: '👎', name: 'Thumbs Down', keywords: 'dislike bad no' },
  { emoji: '👏', name: 'Clapping Hands', keywords: 'applause bravo clap' },
  { emoji: '🙌', name: 'Raised Hands', keywords: 'praise celebrate hooray' },
  { emoji: '🙏', name: 'Folded Hands', keywords: 'pray please thanks' },
  { emoji: '👋', name: 'Waving Hand', keywords: 'hello bye wave' },
  { emoji: '✋', name: 'Raised Hand', keywords: 'stop high five' },
  { emoji: '👊', name: 'Fist Bump', keywords: 'punch bump fist' },
  { emoji: '✌️', name: 'Victory Hand', keywords: 'peace victory' },
  { emoji: '🤝', name: 'Handshake', keywords: 'deal agreement partner' },
  { emoji: '👉', name: 'Point Right', keywords: 'point direction right' },
  { emoji: '👈', name: 'Point Left', keywords: 'point direction left' },
  { emoji: '☝️', name: 'Point Up', keywords: 'point direction up' },
  { emoji: '👇', name: 'Point Down', keywords: 'point direction down' },
  { emoji: '💃', name: 'Dancer', keywords: 'dance woman party' },
  { emoji: '🕺', name: 'Man Dancing', keywords: 'dance man party' },
  { emoji: '🚶', name: 'Walking', keywords: 'walk person' },
  { emoji: '🏃', name: 'Running', keywords: 'run person sprint' },
  { emoji: '🐶', name: 'Dog', keywords: 'dog puppy pet animal' },
  { emoji: '🐱', name: 'Cat', keywords: 'cat kitten pet animal' },
  { emoji: '🐭', name: 'Mouse', keywords: 'mouse rodent animal' },
  { emoji: '🐹', name: 'Hamster', keywords: 'hamster pet animal' },
  { emoji: '🐰', name: 'Rabbit', keywords: 'rabbit bunny animal' },
  { emoji: '🦊', name: 'Fox', keywords: 'fox animal' },
  { emoji: '🐻', name: 'Bear', keywords: 'bear animal' },
  { emoji: '🐼', name: 'Panda', keywords: 'panda animal' },
  { emoji: '🐨', name: 'Koala', keywords: 'koala animal' },
  { emoji: '🐯', name: 'Tiger', keywords: 'tiger animal' },
  { emoji: '🦁', name: 'Lion', keywords: 'lion animal king' },
  { emoji: '🐮', name: 'Cow', keywords: 'cow animal farm' },
  { emoji: '🐷', name: 'Pig', keywords: 'pig animal farm' },
  { emoji: '🐸', name: 'Frog', keywords: 'frog animal' },
  { emoji: '🐵', name: 'Monkey', keywords: 'monkey animal' },
  { emoji: '🐔', name: 'Chicken', keywords: 'chicken animal farm bird' },
  { emoji: '🐧', name: 'Penguin', keywords: 'penguin animal bird' },
  { emoji: '🐦', name: 'Bird', keywords: 'bird animal' },
  { emoji: '🦉', name: 'Owl', keywords: 'owl bird night' },
  { emoji: '🐺', name: 'Wolf', keywords: 'wolf animal' },
  { emoji: '🐴', name: 'Horse', keywords: 'horse animal' },
  { emoji: '🦄', name: 'Unicorn', keywords: 'unicorn fantasy magic' },
  { emoji: '🐝', name: 'Bee', keywords: 'bee insect honey' },
  { emoji: '🦋', name: 'Butterfly', keywords: 'butterfly insect' },
  { emoji: '🐢', name: 'Turtle', keywords: 'turtle animal slow' },
  { emoji: '🐍', name: 'Snake', keywords: 'snake animal' },
  { emoji: '🐙', name: 'Octopus', keywords: 'octopus sea animal' },
  { emoji: '🐬', name: 'Dolphin', keywords: 'dolphin sea animal' },
  { emoji: '🐳', name: 'Whale', keywords: 'whale sea animal' },
  { emoji: '🐟', name: 'Fish', keywords: 'fish sea animal' },
  { emoji: '🦈', name: 'Shark', keywords: 'shark sea animal' },
  { emoji: '🌸', name: 'Cherry Blossom', keywords: 'flower spring' },
  { emoji: '🌹', name: 'Rose', keywords: 'flower love romance' },
  { emoji: '🌻', name: 'Sunflower', keywords: 'flower sun' },
  { emoji: '🌵', name: 'Cactus', keywords: 'plant desert' },
  { emoji: '🌲', name: 'Tree', keywords: 'tree forest nature' },
  { emoji: '🍀', name: 'Four Leaf Clover', keywords: 'luck lucky clover' },
  { emoji: '🌈', name: 'Rainbow', keywords: 'rainbow colorful pride' },
  { emoji: '☀️', name: 'Sun', keywords: 'sun sunny weather' },
  { emoji: '🌙', name: 'Crescent Moon', keywords: 'moon night' },
  { emoji: '☁️', name: 'Cloud', keywords: 'cloud weather sky' },
  { emoji: '⚡', name: 'Lightning Bolt', keywords: 'thunder storm electric power' },
  { emoji: '❄️', name: 'Snowflake', keywords: 'snow cold winter' },
  { emoji: '🌊', name: 'Wave', keywords: 'ocean water sea' },
  { emoji: '🍎', name: 'Apple', keywords: 'apple fruit food' },
  { emoji: '🍌', name: 'Banana', keywords: 'banana fruit food' },
  { emoji: '🍇', name: 'Grapes', keywords: 'grapes fruit food wine' },
  { emoji: '🍓', name: 'Strawberry', keywords: 'strawberry fruit food' },
  { emoji: '🍉', name: 'Watermelon', keywords: 'watermelon fruit summer' },
  { emoji: '🍕', name: 'Pizza', keywords: 'pizza food' },
  { emoji: '🍔', name: 'Burger', keywords: 'burger food hamburger' },
  { emoji: '🍟', name: 'Fries', keywords: 'fries food chips' },
  { emoji: '🌭', name: 'Hot Dog', keywords: 'hotdog food' },
  { emoji: '🍿', name: 'Popcorn', keywords: 'popcorn movie snack' },
  { emoji: '🍩', name: 'Donut', keywords: 'donut sweet dessert' },
  { emoji: '🍪', name: 'Cookie', keywords: 'cookie sweet dessert' },
  { emoji: '🎂', name: 'Birthday Cake', keywords: 'cake birthday party' },
  { emoji: '🍰', name: 'Cake Slice', keywords: 'cake dessert sweet' },
  { emoji: '🍫', name: 'Chocolate', keywords: 'chocolate sweet dessert' },
  { emoji: '☕', name: 'Coffee', keywords: 'coffee drink hot' },
  { emoji: '🍵', name: 'Tea', keywords: 'tea drink hot' },
  { emoji: '🍺', name: 'Beer', keywords: 'beer drink alcohol' },
  { emoji: '🍷', name: 'Wine', keywords: 'wine drink alcohol' },
  { emoji: '🥤', name: 'Cup with Straw', keywords: 'drink soda cup' },
  { emoji: '⚽', name: 'Soccer Ball', keywords: 'soccer football sport' },
  { emoji: '🏀', name: 'Basketball', keywords: 'basketball sport' },
  { emoji: '🏈', name: 'American Football', keywords: 'football sport' },
  { emoji: '⚾', name: 'Baseball', keywords: 'baseball sport' },
  { emoji: '🎾', name: 'Tennis', keywords: 'tennis sport' },
  { emoji: '🏐', name: 'Volleyball', keywords: 'volleyball sport' },
  { emoji: '🎱', name: 'Pool Ball', keywords: 'billiards pool sport' },
  { emoji: '🏓', name: 'Ping Pong', keywords: 'table tennis sport' },
  { emoji: '🎮', name: 'Video Game', keywords: 'game controller play' },
  { emoji: '🎲', name: 'Dice', keywords: 'game dice random' },
  { emoji: '🎨', name: 'Palette', keywords: 'art paint color creative' },
  { emoji: '🎸', name: 'Guitar', keywords: 'music guitar instrument' },
  { emoji: '🎹', name: 'Piano', keywords: 'music piano instrument' },
  { emoji: '🎤', name: 'Microphone', keywords: 'music sing mic' },
  { emoji: '🎧', name: 'Headphones', keywords: 'music listen audio' },
  { emoji: '🎵', name: 'Musical Note', keywords: 'music note song' },
  { emoji: '🎬', name: 'Clapper Board', keywords: 'movie film action director' },
  { emoji: '📸', name: 'Camera Flash', keywords: 'photo camera picture' },
  { emoji: '📷', name: 'Camera', keywords: 'photo camera picture' },
  { emoji: '🚗', name: 'Car', keywords: 'car vehicle drive' },
  { emoji: '🚕', name: 'Taxi', keywords: 'taxi cab car' },
  { emoji: '🚲', name: 'Bicycle', keywords: 'bike bicycle ride' },
  { emoji: '✈️', name: 'Airplane', keywords: 'plane flight travel' },
  { emoji: '🚀', name: 'Rocket', keywords: 'rocket space launch fast' },
  { emoji: '🛸', name: 'UFO', keywords: 'ufo alien space' },
  { emoji: '⛵', name: 'Sailboat', keywords: 'boat sail sea' },
  { emoji: '🚢', name: 'Ship', keywords: 'ship boat sea travel' },
  { emoji: '🏠', name: 'House', keywords: 'home house building' },
  { emoji: '🏢', name: 'Office Building', keywords: 'building office work' },
  { emoji: '🏰', name: 'Castle', keywords: 'castle fantasy building' },
  { emoji: '🗻', name: 'Mountain', keywords: 'mountain nature' },
  { emoji: '🏖️', name: 'Beach', keywords: 'beach vacation summer' },
  { emoji: '🎡', name: 'Ferris Wheel', keywords: 'fair carnival amusement' },
  { emoji: '💡', name: 'Light Bulb', keywords: 'idea light bright' },
  { emoji: '🔦', name: 'Flashlight', keywords: 'light torch dark' },
  { emoji: '🔑', name: 'Key', keywords: 'key lock unlock' },
  { emoji: '🔒', name: 'Locked', keywords: 'lock secure private' },
  { emoji: '🔓', name: 'Unlocked', keywords: 'unlock open' },
  { emoji: '💰', name: 'Money Bag', keywords: 'money cash rich' },
  { emoji: '💵', name: 'Dollar Bill', keywords: 'money cash dollar' },
  { emoji: '💳', name: 'Credit Card', keywords: 'money card pay' },
  { emoji: '💎', name: 'Gem Stone', keywords: 'diamond jewel precious' },
  { emoji: '🎁', name: 'Gift', keywords: 'present gift box' },
  { emoji: '🔔', name: 'Bell', keywords: 'bell notification ring' },
  { emoji: '📢', name: 'Loudspeaker', keywords: 'announcement megaphone' },
  { emoji: '📣', name: 'Megaphone', keywords: 'announce shout' },
  { emoji: '📌', name: 'Pin', keywords: 'pushpin location mark' },
  { emoji: '📍', name: 'Round Pin', keywords: 'location map mark' },
  { emoji: '📎', name: 'Paperclip', keywords: 'attach clip office' },
  { emoji: '✏️', name: 'Pencil', keywords: 'write draw pencil' },
  { emoji: '🖊️', name: 'Pen', keywords: 'write pen ink' },
  { emoji: '📝', name: 'Memo', keywords: 'note write document' },
  { emoji: '📚', name: 'Books', keywords: 'books read study library' },
  { emoji: '📖', name: 'Open Book', keywords: 'book read study' },
  { emoji: '💻', name: 'Laptop', keywords: 'computer laptop work tech' },
  { emoji: '🖥️', name: 'Desktop Computer', keywords: 'computer tech work' },
  { emoji: '📱', name: 'Mobile Phone', keywords: 'phone mobile tech' },
  { emoji: '⌚', name: 'Watch', keywords: 'watch time clock' },
  { emoji: '⏰', name: 'Alarm Clock', keywords: 'clock time alarm' },
  { emoji: '📅', name: 'Calendar', keywords: 'date calendar schedule' },
  { emoji: '📊', name: 'Bar Chart', keywords: 'chart data graph stats' },
  { emoji: '📈', name: 'Chart Increasing', keywords: 'growth chart stats up' },
  { emoji: '📉', name: 'Chart Decreasing', keywords: 'decline chart stats down' },
  { emoji: '🔍', name: 'Magnifying Glass', keywords: 'search find zoom' },
  { emoji: '⚙️', name: 'Gear', keywords: 'settings config gear' },
  { emoji: '🔧', name: 'Wrench', keywords: 'tool fix repair' },
  { emoji: '🔨', name: 'Hammer', keywords: 'tool build fix' },
  { emoji: '🧲', name: 'Magnet', keywords: 'magnet attract' },
  { emoji: '🧪', name: 'Test Tube', keywords: 'science lab chemistry' },
  { emoji: '🔬', name: 'Microscope', keywords: 'science lab research' },
  { emoji: '🧬', name: 'DNA', keywords: 'dna genetics science' },
  { emoji: '🌍', name: 'Globe', keywords: 'earth world globe map' },
  { emoji: '🗺️', name: 'World Map', keywords: 'map travel world' },
  { emoji: '🧭', name: 'Compass', keywords: 'compass direction navigate' },
  { emoji: '⏳', name: 'Hourglass', keywords: 'time wait hourglass' },
  { emoji: '♻️', name: 'Recycle', keywords: 'recycle green eco' },
  { emoji: '☮️', name: 'Peace Symbol', keywords: 'peace symbol' },
  { emoji: '✅', name: 'Check Mark', keywords: 'check done yes correct' },
  { emoji: '❌', name: 'Cross Mark', keywords: 'x wrong no cancel' },
  { emoji: '❓', name: 'Question Mark', keywords: 'question ask confused' },
  { emoji: '❗', name: 'Exclamation Mark', keywords: 'exclamation warning alert' },
  { emoji: '⚠️', name: 'Warning', keywords: 'warning caution alert' },
  { emoji: '🚫', name: 'Prohibited', keywords: 'no stop forbidden' },
  { emoji: '♥️', name: 'Heart Suit', keywords: 'heart love card' },
  { emoji: '🎯', name: 'Direct Hit', keywords: 'target goal bullseye' },
  { emoji: '🧩', name: 'Puzzle Piece', keywords: 'puzzle solve piece' },
  { emoji: '🎓', name: 'Graduation Cap', keywords: 'graduate education school' },
  { emoji: '🧸', name: 'Teddy Bear', keywords: 'teddy bear toy' },
  { emoji: '👑', name: 'Crown', keywords: 'crown king queen royal' },
  { emoji: '💀', name: 'Skull', keywords: 'skull death danger' },
  { emoji: '👻', name: 'Ghost', keywords: 'ghost spooky halloween' },
  { emoji: '👽', name: 'Alien', keywords: 'alien ufo space' },
  { emoji: '🤖', name: 'Robot', keywords: 'robot ai tech machine' },
]

/** Renders an emoji as an inline SVG data URL, same-origin so it never taints the canvas. */
export function emojiToDataUrl(emoji, size = 128) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${size}" height="${size}"><text x="12" y="13" font-size="19" text-anchor="middle" dominant-baseline="central">${emoji}</text></svg>`
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`
}
