import './TemplateSelector.css'

const templates = {
  pas: {
    name: 'PAS',
    description: 'Problem, Agitate, Solution',
    slides: [
      {
        id: 1,
        content: 'Problem',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Explain the problem',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'Agitate',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Make the problem bigger',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Solution',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Explain your solution',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  aida: {
    name: 'AIDA',
    description: 'Attention, Interest, Desire, Action',
    slides: [
      {
        id: 1,
        content: 'Attention',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Capture attention',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'Interest',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Build interest',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Desire',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Create desire',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 7,
        content: 'Action',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 8,
        content: 'Call to action',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  story: {
    name: 'Story',
    description: 'Classic story structure with hero\'s journey',
    slides: [
      {
        id: 1,
        content: 'The Scene',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Set the scene and introduce the main character',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'The Problem',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Describe their problem',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Failed Attempts',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Show how they try to fix it, but it doesn\'t work',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 7,
        content: 'The Crisis',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 8,
        content: 'Escalate the problem until it\'s as bad as it can possibly get',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 9,
        content: 'The Insight',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 10,
        content: 'Reveal the "aha!" moment that leads to one final attempt',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 11,
        content: 'The Solution',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 12,
        content: 'Show the hero taking action on the solution, and it works',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 13,
        content: 'The New Life',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 14,
        content: 'Describe the hero\'s new life, now that the problem has been fixed',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 15,
        content: 'The Lesson',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 16,
        content: 'Call out your specific audience and clearly state the moral or lesson they should take from the story',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  bab: {
    name: 'BAB',
    description: 'Before, After, Bridge',
    slides: [
      {
        id: 1,
        content: 'Before',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Describe the current situation',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'After',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Paint the picture of the desired future',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Bridge',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Show how to get from before to after',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  hookStoryAsk: {
    name: 'Hook Story Ask',
    description: 'Hook the audience, tell a story, make the ask',
    slides: [
      {
        id: 1,
        content: 'The Hook',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Capture attention with a compelling opening',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'The Story',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Tell your story',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'The Ask',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Make your call to action',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  whatSoWhatNowWhat: {
    name: 'What So What Now What',
    description: 'Explain what it is, why it matters, what to do next',
    slides: [
      {
        id: 1,
        content: 'What',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Explain what it is',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'So What',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Why does it matter?',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Now What',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'What should we do next?',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  featuresBenefitsProof: {
    name: 'Features Benefits Proof',
    description: 'Show features, their benefits, and proof points',
    slides: [
      {
        id: 1,
        content: 'Features',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Show your key features',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'Benefits',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Explain the benefits to your audience',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Proof',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Provide evidence and proof points',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  problemSolutionBenefits: {
    name: 'Problem Solution Benefits',
    description: 'Problem, Solution, and Benefits structure',
    slides: [
      {
        id: 1,
        content: 'Problem',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Identify the problem',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'Solution',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Present your solution',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Benefits',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Highlight the key benefits',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  heroJourney: {
    name: 'Hero\'s Journey',
    description: 'Classic hero\'s journey narrative structure',
    slides: [
      {
        id: 1,
        content: 'Ordinary World',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Show the hero in their normal world',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'Call to Adventure',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'The challenge or opportunity appears',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Refusal of the Call',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Show initial hesitation or resistance',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 7,
        content: 'Crossing the Threshold',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 8,
        content: 'The hero commits to the journey',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 9,
        content: 'Tests and Allies',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 10,
        content: 'Challenges faced and help received',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 11,
        content: 'Approach to the Inmost Cave',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 12,
        content: 'Preparing for the ultimate challenge',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 13,
        content: 'Ordeal',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 14,
        content: 'The biggest challenge or crisis',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 15,
        content: 'Reward',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 16,
        content: 'The hero gains what they sought',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 17,
        content: 'Return',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 18,
        content: 'Returning home transformed',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  learnPracticeApply: {
    name: 'Learn-Practice-Apply',
    description: 'Classic module structure: Learn concepts, practice skills, apply knowledge',
    slides: [
      {
        id: 1,
        content: 'Module Overview',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'What you\'ll learn in this module',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'Learn',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Core concepts and theory',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Key principles to understand',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Practice',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 7,
        content: 'Hands-on exercises and activities',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 8,
        content: 'Step-by-step guided practice',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 9,
        content: 'Apply',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 10,
        content: 'Real-world application project',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 11,
        content: 'Put your knowledge into action',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  foundationBuildingMastery: {
    name: 'Foundation-Building-Mastery',
    description: 'Progressive skill building: Start with basics, build up, achieve mastery',
    slides: [
      {
        id: 1,
        content: 'Module Introduction',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'Your learning journey in this module',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'Foundation',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Essential fundamentals you need to know',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Core building blocks',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'Building',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 7,
        content: 'Intermediate skills and techniques',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 8,
        content: 'Connecting concepts and expanding knowledge',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 9,
        content: 'Mastery',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 10,
        content: 'Advanced techniques and expert strategies',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 11,
        content: 'Achieving proficiency and confidence',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  },
  problemSolutionImplementation: {
    name: 'Problem-Solution-Implementation',
    description: 'Practical course structure: Identify problem, learn solution, implement it',
    slides: [
      {
        id: 1,
        content: 'Module Overview',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 2,
        content: 'What challenge will we solve?',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 3,
        content: 'The Problem',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 4,
        content: 'Identify the specific challenge',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 5,
        content: 'Why this problem matters',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 6,
        content: 'The Solution',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 7,
        content: 'Learn the proven approach',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 8,
        content: 'Key strategies and methods',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 9,
        content: 'Implementation',
        subtitle: '',
        imageUrl: '',
        layout: 'section',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 10,
        content: 'Step-by-step implementation guide',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      },
      {
        id: 11,
        content: 'Put it into practice right away',
        subtitle: '',
        imageUrl: '',
        layout: 'default',
        gradientStrength: 0.7,
        flipHorizontal: false,
        backgroundOpacity: 1.0,
        gradientFlipped: false,
        imageScale: 1.0,
        imagePositionX: 50,
        imagePositionY: 50,
        textHeadingLevel: null,
        subtitleHeadingLevel: null
      }
    ]
  }
}

function TemplateSelector({ onLoadTemplate }) {
  const handleLoadTemplate = (templateKey) => {
    const template = templates[templateKey]
    if (template && window.confirm(`Load ${template.name} template? This will replace all current slides.`)) {
      onLoadTemplate(template.slides, templateKey)
    }
  }

  return (
    <div className="template-selector">
      <h3 className="template-selector-title">TEMPLATES</h3>
      <div className="template-list">
        {Object.entries(templates).map(([key, template]) => (
          <button
            key={key}
            className="template-item"
            onClick={() => handleLoadTemplate(key)}
            title={template.description}
          >
            <div className="template-name">{template.name}</div>
            <div className="template-description">{template.description}</div>
          </button>
        ))}
      </div>
    </div>
  )
}

export default TemplateSelector
