// Google Material Symbols (Material Symbols Outlined) – id is the icon name for the font
export const POSTIT_ICONS = [
  { id: 'none', name: 'None' },
  { id: 'home', name: 'Home' },
  { id: 'favorite', name: 'Favorite' },
  { id: 'star', name: 'Star' },
  { id: 'search', name: 'Search' },
  { id: 'settings', name: 'Settings' },
  { id: 'person', name: 'Person' },
  { id: 'add', name: 'Add' },
  { id: 'edit', name: 'Edit' },
  { id: 'delete', name: 'Delete' },
  { id: 'close', name: 'Close' },
  { id: 'check', name: 'Check' },
  { id: 'check_circle', name: 'Check circle' },
  { id: 'link', name: 'Link' },
  { id: 'share', name: 'Share' },
  { id: 'content_copy', name: 'Copy' },
  { id: 'mail', name: 'Mail' },
  { id: 'send', name: 'Send' },
  { id: 'chat', name: 'Chat' },
  { id: 'message', name: 'Message' },
  { id: 'call', name: 'Call' },
  { id: 'email', name: 'Email' },
  { id: 'inbox', name: 'Inbox' },
  { id: 'draft', name: 'Draft' },
  { id: 'archive', name: 'Archive' },
  { id: 'folder', name: 'Folder' },
  { id: 'folder_open', name: 'Folder open' },
  { id: 'description', name: 'Description' },
  { id: 'note', name: 'Note' },
  { id: 'note_add', name: 'Note add' },
  { id: 'article', name: 'Article' },
  { id: 'menu_book', name: 'Menu book' },
  { id: 'book', name: 'Book' },
  { id: 'bookmark', name: 'Bookmark' },
  { id: 'tag', name: 'Tag' },
  { id: 'label', name: 'Label' },
  { id: 'lightbulb', name: 'Lightbulb' },
  { id: 'lightbulb_outline', name: 'Idea' },
  { id: 'thermostat', name: 'Thermostat' },
  { id: 'cloud', name: 'Cloud' },
  { id: 'wb_sunny', name: 'Sun' },
  { id: 'nights_stay', name: 'Night' },
  { id: 'water_drop', name: 'Water' },
  { id: 'air', name: 'Air' },
  { id: 'ac_unit', name: 'Snow' },
  { id: 'terrain', name: 'Terrain' },
  { id: 'place', name: 'Place' },
  { id: 'map', name: 'Map' },
  { id: 'flag', name: 'Flag' },
  { id: 'calendar_today', name: 'Calendar' },
  { id: 'schedule', name: 'Schedule' },
  { id: 'alarm', name: 'Alarm' },
  { id: 'timer', name: 'Timer' },
  { id: 'history', name: 'History' },
  { id: 'trending_up', name: 'Trending up' },
  { id: 'trending_down', name: 'Trending down' },
  { id: 'bar_chart', name: 'Bar chart' },
  { id: 'pie_chart', name: 'Pie chart' },
  { id: 'show_chart', name: 'Line chart' },
  { id: 'analytics', name: 'Analytics' },
  { id: 'account_balance', name: 'Account balance' },
  { id: 'attach_money', name: 'Money' },
  { id: 'savings', name: 'Savings' },
  { id: 'payment', name: 'Payment' },
  { id: 'credit_card', name: 'Credit card' },
  { id: 'shopping_cart', name: 'Shopping cart' },
  { id: 'store', name: 'Store' },
  { id: 'local_offer', name: 'Offer' },
  { id: 'work', name: 'Work' },
  { id: 'business', name: 'Business' },
  { id: 'business_center', name: 'Business center' },
  { id: 'school', name: 'School' },
  { id: 'rocket_launch', name: 'Rocket' },
  { id: 'public', name: 'Public' },
  { id: 'language', name: 'Language' },
  { id: 'computer', name: 'Computer' },
  { id: 'phone_android', name: 'Phone' },
  { id: 'tablet', name: 'Tablet' },
  { id: 'watch', name: 'Watch' },
  { id: 'headphones', name: 'Headphones' },
  { id: 'speaker', name: 'Speaker' },
  { id: 'camera_alt', name: 'Camera' },
  { id: 'photo_camera', name: 'Photo camera' },
  { id: 'videocam', name: 'Videocam' },
  { id: 'mic', name: 'Mic' },
  { id: 'volume_up', name: 'Volume up' },
  { id: 'music_note', name: 'Music note' },
  { id: 'play_arrow', name: 'Play' },
  { id: 'pause', name: 'Pause' },
  { id: 'stop', name: 'Stop' },
  { id: 'notifications', name: 'Notifications' },
  { id: 'notifications_off', name: 'Notifications off' },
  { id: 'group', name: 'Group' },
  { id: 'groups', name: 'Groups' },
  { id: 'person_add', name: 'Person add' },
  { id: 'handshake', name: 'Handshake' },
  { id: 'psychology', name: 'Psychology' },
  { id: 'science', name: 'Science' },
  { id: 'biotech', name: 'Biotech' },
  { id: 'code', name: 'Code' },
  { id: 'terminal', name: 'Terminal' },
  { id: 'bug_report', name: 'Bug' },
  { id: 'build', name: 'Build' },
  { id: 'construction', name: 'Construction' },
  { id: 'engineering', name: 'Engineering' },
  { id: 'design_services', name: 'Design' },
  { id: 'palette', name: 'Palette' },
  { id: 'brush', name: 'Brush' },
  { id: 'image', name: 'Image' },
  { id: 'photo_library', name: 'Photo library' },
  { id: 'video_library', name: 'Video library' },
  { id: 'movie', name: 'Movie' },
  { id: 'sports_esports', name: 'Gaming' },
  { id: 'sports_soccer', name: 'Soccer' },
  { id: 'fitness_center', name: 'Fitness' },
  { id: 'restaurant', name: 'Restaurant' },
  { id: 'local_cafe', name: 'Cafe' },
  { id: 'flight', name: 'Flight' },
  { id: 'directions_car', name: 'Car' },
  { id: 'train', name: 'Train' },
  { id: 'directions_boat', name: 'Boat' },
  { id: 'two_wheeler', name: 'Bike' },
  { id: 'local_hospital', name: 'Hospital' },
  { id: 'vaccines', name: 'Vaccines' },
  { id: 'medication', name: 'Medication' },
  { id: 'eco', name: 'Eco' },
  { id: 'park', name: 'Park' },
  { id: 'pets', name: 'Pets' },
  { id: 'spa', name: 'Spa' },
  { id: 'self_improvement', name: 'Meditation' },
  { id: 'volunteer_activism', name: 'Volunteer' },
  { id: 'handyman', name: 'Handyman' },
  { id: 'plumbing', name: 'Plumbing' },
  { id: 'electrical_services', name: 'Electrical' },
  { id: 'cleaning_services', name: 'Cleaning' },
  { id: 'security', name: 'Security' },
  { id: 'lock', name: 'Lock' },
  { id: 'lock_open', name: 'Lock open' },
  { id: 'key', name: 'Key' },
  { id: 'visibility', name: 'Visibility' },
  { id: 'visibility_off', name: 'Visibility off' },
  { id: 'shield', name: 'Shield' },
  { id: 'warning', name: 'Warning' },
  { id: 'error', name: 'Error' },
  { id: 'info', name: 'Info' },
  { id: 'help', name: 'Help' },
  { id: 'tips_and_updates', name: 'Tips' },
  { id: 'campaign', name: 'Campaign' },
  { id: 'record_voice_over', name: 'Voice' },
  { id: 'translate', name: 'Translate' },
  { id: 'spellcheck', name: 'Spellcheck' },
  { id: 'summarize', name: 'Summarize' },
  { id: 'smart_toy', name: 'AI' },
  { id: 'auto_awesome', name: 'Auto awesome' },
  { id: 'bolt', name: 'Bolt' },
  { id: 'flash_on', name: 'Flash' },
  { id: 'power', name: 'Power' },
  { id: 'battery_charging_full', name: 'Battery' },
  { id: 'wifi', name: 'Wi‑Fi' },
  { id: 'bluetooth', name: 'Bluetooth' },
  { id: 'router', name: 'Router' },
  { id: 'storage', name: 'Storage' },
  { id: 'cloud_upload', name: 'Cloud upload' },
  { id: 'cloud_download', name: 'Cloud download' },
  { id: 'download', name: 'Download' },
  { id: 'upload', name: 'Upload' },
  { id: 'attach_file', name: 'Attach file' },
  { id: 'insert_drive_file', name: 'Insert file' },
  { id: 'folder_special', name: 'Folder special' },
  { id: 'task_alt', name: 'Task' },
  { id: 'task', name: 'Task list' },
  { id: 'checklist', name: 'Checklist' },
  { id: 'list', name: 'List' },
  { id: 'view_list', name: 'View list' },
  { id: 'grid_view', name: 'Grid view' },
  { id: 'dashboard', name: 'Dashboard' },
  { id: 'space_dashboard', name: 'Space dashboard' },
  { id: 'table_chart', name: 'Table' },
  { id: 'insights', name: 'Insights' },
  { id: 'query_stats', name: 'Query stats' },
  { id: 'timeline', name: 'Timeline' },
  { id: 'event', name: 'Event' },
  { id: 'event_note', name: 'Event note' },
  { id: 'today', name: 'Today' },
  { id: 'date_range', name: 'Date range' },
  { id: 'alarm_on', name: 'Alarm on' },
  { id: 'hourglass_empty', name: 'Hourglass' },
  { id: 'timer_off', name: 'Timer off' },
  { id: 'access_time', name: 'Access time' },
  { id: 'update', name: 'Update' },
  { id: 'sync', name: 'Sync' },
  { id: 'cached', name: 'Cached' },
  { id: 'refresh', name: 'Refresh' },
  { id: 'autorenew', name: 'Autorenew' },
  { id: 'arrow_back', name: 'Arrow back' },
  { id: 'arrow_forward', name: 'Arrow forward' },
  { id: 'expand_more', name: 'Expand more' },
  { id: 'expand_less', name: 'Expand less' },
  { id: 'menu', name: 'Menu' },
  { id: 'more_vert', name: 'More' },
  { id: 'apps', name: 'Apps' },
  { id: 'dashboard_customize', name: 'Customize' },
  { id: 'tune', name: 'Tune' },
  { id: 'filter_list', name: 'Filter' },
  { id: 'sort', name: 'Sort' },
  { id: 'zoom_in', name: 'Zoom in' },
  { id: 'zoom_out', name: 'Zoom out' },
  { id: 'fullscreen', name: 'Fullscreen' },
  { id: 'open_in_new', name: 'Open in new' },
  { id: 'launch', name: 'Launch' },
  { id: 'push_pin', name: 'Push pin' },
  { id: 'bookmark_add', name: 'Bookmark add' },
  { id: 'bookmark_remove', name: 'Bookmark remove' },
  { id: 'outlined_flag', name: 'Flag outline' },
  { id: 'gps_fixed', name: 'GPS' },
  { id: 'target', name: 'Target' },
  { id: 'my_location', name: 'My location' },
  { id: 'explore', name: 'Explore' },
  { id: 'travel_explore', name: 'Travel' },
  { id: 'hiking', name: 'Hiking' },
  { id: 'sailing', name: 'Sailing' },
  { id: 'kayaking', name: 'Kayaking' },
  { id: 'downhill_skiing', name: 'Skiing' },
  { id: 'sports_basketball', name: 'Basketball' },
  { id: 'sports_tennis', name: 'Tennis' },
  { id: 'golf_course', name: 'Golf' },
  { id: 'casino', name: 'Casino' },
  { id: 'theater_comedy', name: 'Theater' },
  { id: 'museum', name: 'Museum' },
  { id: 'library_books', name: 'Library' },
  { id: 'menu_book', name: 'Menu book' },
  { id: 'auto_stories', name: 'Stories' },
  { id: 'newspaper', name: 'Newspaper' },
  { id: 'rss_feed', name: 'RSS' },
  { id: 'podcasts', name: 'Podcasts' },
  { id: 'subscriptions', name: 'Subscriptions' },
  { id: 'playlist_add', name: 'Playlist add' },
  { id: 'queue_music', name: 'Queue music' },
  { id: 'repeat', name: 'Repeat' },
  { id: 'shuffle', name: 'Shuffle' },
  { id: 'hearing', name: 'Hearing' },
  { id: 'graphic_eq', name: 'Graphic eq' },
  { id: 'speed', name: 'Speed' },
  { id: 'slow_motion_video', name: 'Slow motion' },
  { id: 'high_quality', name: 'Quality' },
  { id: 'hd', name: 'HD' },
  { id: '4k', name: '4K' },
  { id: 'subtitles', name: 'Subtitles' },
  { id: 'closed_caption', name: 'Closed caption' },
  { id: 'mic_none', name: 'Mic none' },
  { id: 'mic_off', name: 'Mic off' },
  { id: 'volume_off', name: 'Volume off' },
  { id: 'volume_mute', name: 'Volume mute' },
  { id: 'videocam_off', name: 'Videocam off' },
  { id: 'call_end', name: 'Call end' },
  { id: 'call_made', name: 'Call made' },
  { id: 'call_received', name: 'Call received' },
  { id: 'ring_volume', name: 'Ring' },
  { id: 'phone_in_talk', name: 'Phone in talk' },
  { id: 'contact_mail', name: 'Contact mail' },
  { id: 'contact_phone', name: 'Contact phone' },
  { id: 'alternate_email', name: 'Email alt' },
  { id: 'mark_as_unread', name: 'Mark unread' },
  { id: 'mark_email_read', name: 'Mark read' },
  { id: 'forward', name: 'Forward' },
  { id: 'reply', name: 'Reply' },
  { id: 'reply_all', name: 'Reply all' },
  { id: 'block', name: 'Block' },
  { id: 'report', name: 'Report' },
  { id: 'feedback', name: 'Feedback' },
  { id: 'support', name: 'Support' },
  { id: 'live_help', name: 'Live help' },
  { id: 'quiz', name: 'Quiz' },
  { id: 'cast_for_education', name: 'Education' },
  { id: 'science', name: 'Science' },
  { id: 'calculate', name: 'Calculate' },
  { id: 'functions', name: 'Functions' },
  { id: 'formula', name: 'Formula' },
];

export const DEFAULT_ICON_ID = 'none';
export const getIconById = (id) => POSTIT_ICONS.find((i) => i.id === (id || DEFAULT_ICON_ID)) || POSTIT_ICONS[0];
