import { AppData, Integration, ResearchSource, WorkflowAction } from "./types";

export const PIPELINE_STATUSES = ["Idea", "Researched", "Ideated", "Scripted", "Filmed", "Posted"] as const;

export const NAV_ITEMS = [
  { label: "Dashboard", href: "/" },
  { label: "Brand Setup", href: "/brand-setup" },
  { label: "Research", href: "/research" },
  { label: "Pipeline", href: "/pipeline" },
  { label: "Multiply", href: "/multiply" },
  { label: "Script", href: "/script" },
  { label: "Film", href: "/film" },
  { label: "Post", href: "/post" },
  { label: "Analytics", href: "/analytics" },
  { label: "Competitor Analysis", href: "/competitor-analysis" },
  { label: "Reference Files", href: "/reference-files" },
  { label: "Settings / Integrations", href: "/settings-integrations" },
  { label: "Video Downloader", href: "/video-downloader" },
] as const;

export const RESEARCH_SOURCES: ResearchSource[] = [
  "X / Twitter",
  "Reddit",
  "GitHub Trending",
  "Tech news",
  "Instagram",
  "YouTube",
  "TikTok",
  "LinkedIn",
  "Manual notes",
];

export const WORKFLOW_ACTIONS: WorkflowAction[] = [
  { id: "daily", name: "Daily Content Researcher", description: "Find trend-backed opportunities.", inputs: ["topic", "audience", "sources"], outputFormat: "10 scored ideas" },
  { id: "ideator", name: "Content Ideator", description: "Create multiple angles from one idea.", inputs: ["idea", "voice"], outputFormat: "5 variations" },
  { id: "scripter", name: "Content Scripter", description: "Generate filming card and captions.", inputs: ["idea", "references"], outputFormat: "Script card" },
  { id: "post", name: "Post Content", description: "Prepare manual posting checklist.", inputs: ["filmed content"], outputFormat: "Posting plan" },
  { id: "analysis", name: "Shortform Analysis", description: "Summarize what performs best.", inputs: ["analytics entries"], outputFormat: "Action list" },
  { id: "competitor", name: "Competitor Analyst", description: "Find patterns and exploitable gaps.", inputs: ["profile", "notes"], outputFormat: "Competitor report" },
  { id: "video-ref", name: "Video Downloader Placeholder", description: "Store URL and notes only in v1.", inputs: ["video URL"], outputFormat: "Saved reference" },
];

const integrationRows = [
  ["apify", "Apify", "Run scraping actors for research", "Apify API key"],
  ["airtable", "Airtable", "Sync pipeline into Airtable", "Airtable PAT + base ID"],
  ["supabase", "Supabase", "Persist to cloud database", "Project URL + key"],
  ["dropbox", "Dropbox", "Store filmed assets", "Dropbox app token"],
  ["openai", "OpenAI", "AI generation engine", "OpenAI API key"],
  ["anthropic", "Anthropic", "Alternative model provider", "Anthropic API key"],
  ["perplexity", "Perplexity", "Web-grounded research", "Perplexity API key"],
  ["youtube-data", "YouTube Data API", "YouTube insights and metadata", "Google API setup"],
  ["instagram-graph", "Instagram Graph API", "Reels/profile insights", "Meta app setup"],
  ["tiktok", "TikTok API", "TikTok post + analytics", "TikTok API setup"],
  ["reddit", "Reddit API", "Subreddit trend insights", "Reddit app credentials"],
  ["x", "X API", "X trend and engagement data", "X bearer token"],
  ["linkedin", "LinkedIn API", "LinkedIn publishing + insights", "LinkedIn app setup"],
  ["scheduler", "Social media scheduler", "Queue posts to scheduler", "Scheduler API key"],
] as const;

const seedIntegrations: Integration[] = integrationRows.map(([id, name, description, requiredSetup]) => ({
  id,
  name,
  description,
  requiredSetup,
  status: "Not connected",
}));

export const defaultData: AppData = {
  brandProfile: {
    businessName: "Filip Lindström",
    whatIDo: "I coach creators and founders to build AI-assisted content systems.",
    platformsAndHandles: "LinkedIn, Instagram, YouTube Shorts, TikTok, X, Threads",
    nicheKeywords: "coaching, creativity, course creation, AI-assisted content systems",
    brandVoice: "direct, warm, strategic, slightly playful, practical",
    alwaysRules: "Always include one practical next step.",
    neverRules: "Never use vague generic advice.",
    audienceDescription: "Creator-educators and solopreneurs growing authority online.",
    speakingStyle: "Direct bullet-point storytelling with practical examples.",
    ctaPreferences: "Invite comments and saves, then soft CTA.",
    contentPillars: "Creator systems, AI workflows, consistency mindset",
    offerDescription: "Coaching + templates for repeatable short-form content.",
    preferredVideoFormats: "Talking head, demo walkthrough, comparison, quick case study",
    noGoTopics: "Politics, gossip, drama",
  },
  ideas: [
    {
      id: "seed-instagram",
      title: "The 20-minute content machine sprint",
      whyTrending: "Creators want systems that remove daily posting anxiety.",
      source: "Mock Instagram creator trend placeholder",
      selectedSource: "Instagram",
      audienceSizeScore: 8,
      demoAbilityScore: 9,
      hookPotentialScore: 8,
      suggestedAngle: "Show the sprint template live in a phone-style view.",
      suggestedFormat: "Tutorial",
      recommendedPlatform: "Instagram",
      status: "Researched",
      hook: "If your content is random, steal this 20-minute sprint.",
      createdAt: new Date().toISOString(),
    },
    {
      id: "seed-youtube",
      title: "Why creators stay stuck in idea mode",
      whyTrending: "Short educational takes on consistency are highly saved.",
      source: "Mock YouTube Shorts trend placeholder",
      selectedSource: "YouTube",
      audienceSizeScore: 9,
      demoAbilityScore: 7,
      hookPotentialScore: 9,
      suggestedAngle: "Compare inspiration-based posting vs system-based posting.",
      suggestedFormat: "Hot take",
      recommendedPlatform: "YouTube Shorts",
      status: "Idea",
      hook: "The real reason your channel feels inconsistent is your workflow.",
      createdAt: new Date().toISOString(),
    },
    {
      id: "seed-reddit",
      title: "3 pain points from Reddit creators",
      whyTrending: "Pain-first creator content drives comments and saves.",
      source: "Mock Reddit trend placeholder",
      selectedSource: "Reddit",
      audienceSizeScore: 7,
      demoAbilityScore: 8,
      hookPotentialScore: 7,
      suggestedAngle: "Turn raw pain points into fast-scripted ideas.",
      suggestedFormat: "Checklist",
      recommendedPlatform: "LinkedIn",
      status: "Ideated",
      hook: "I pulled 3 pain points from Reddit and turned them into content angles.",
      createdAt: new Date().toISOString(),
    },
    {
      id: "seed-x",
      title: "X thread hooks that convert to short-form",
      whyTrending: "Structured hook frameworks are repeatedly reused.",
      source: "Mock X trend placeholder",
      selectedSource: "X / Twitter",
      audienceSizeScore: 8,
      demoAbilityScore: 6,
      hookPotentialScore: 9,
      suggestedAngle: "Break one thread into 5 hooks and test.",
      suggestedFormat: "Comparison",
      recommendedPlatform: "X",
      status: "Scripted",
      hook: "Most hooks fail because this sentence is missing.",
      createdAt: new Date().toISOString(),
    },
    {
      id: "seed-linkedin",
      title: "45-second LinkedIn case study formula",
      whyTrending: "B2B creators engage with short tactical case studies.",
      source: "Mock LinkedIn trend placeholder",
      selectedSource: "LinkedIn",
      audienceSizeScore: 7,
      demoAbilityScore: 8,
      hookPotentialScore: 8,
      suggestedAngle: "Use one before/after and one method.",
      suggestedFormat: "Story",
      recommendedPlatform: "LinkedIn",
      status: "Filmed",
      hook: "A 45-second case study can outperform your 10-minute explanation.",
      createdAt: new Date().toISOString(),
    },
  ],
  variations: [],
  scripts: [],
  analytics: [],
  references: [
    { id: "avatar.md", title: "avatar.md", content: "## Audience Avatar\n- Coaches and creators\n- Wants consistent leads\n- Needs practical systems" },
    { id: "scripting-voice.md", title: "scripting-voice.md", content: "## Scripting Voice\n- Open with tension\n- Keep lines short\n- Stay tactical and warm" },
    { id: "viral-content-patterns.md", title: "viral-content-patterns.md", content: "## Viral Patterns\n1. Contrarian opener\n2. Framework\n3. Real example" },
    { id: "hook-swipe-file.md", title: "hook-swipe-file.md", content: "## Hook Swipe File\n- Stop posting random content\n- Do this before your next video\n- The mistake killing your reach" },
  ],
  integrations: seedIntegrations,
  competitorProfiles: [],
  competitorAnalyses: [],
  videoReferences: [],
  apiKeys: {},
};
